---
dependency:
  name: galaxy
  # options:
  #  role-file: requirements.yml
  #  requirements-file: requirements.yml
driver:
  name: vagrant
platforms:
  - name: centos7
    instance_raw_config_args:
      - 'vagrant.plugins = ["vagrant-libvirt"]'
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
    box: centos/7
    memory: 1024
    cpus: 1
    provider_options:
      video_type: "'vga'"
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
